memory_limit = 512M
upload_max_filesize = 10M
post_max_size = 12M
max_execution_time = 120
date.timezone = America/La_Paz
expose_php = Off

opcache.enable = 1
opcache.memory_consumption = 128
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = ${PHP_OPCACHE_VALIDATE_TIMESTAMPS}
